Main 912
mona12rst/AlkmaarMania pull request #345
Opened 2022-05-10 21:00 UTC by mona12rst

2022-05-10 21:03 UTC, abbydiode requested changes

2022-05-10 21:03 UTC, abbydiode commented on Assets/Scripts/Logic/Player.cs
> +	public float Experience { get;set; }
Why is this no longer private?

2022-05-10 21:03 UTC, abbydiode commented on Assets/Scripts/UI/UpgradeButton.cs
> +            Debug.Log($"upgrade cost is: {currentUpgradeCost}");
I think we should try not to commit any debug code

2022-05-10 21:03 UTC, abbydiode commented on Assets/Scripts/UI/UpgradeDetailsController.cs
> +        Debug.Log($"is this shit null? : {building.buildingItems.Count}");
Same comment as above

2022-05-11 09:08 UTC, Zarmina approved these changes

2022-05-11 09:11 UTC, merged